### ISSUE TITLE
[Bug] Error occurred when only type /ifp command without args

### ISSUE THREAD

**Issue by HaHaWTH** [heyxmirko/ImageFireworksPro#1]
Environment: 
Azul zulu JDK 21.0.2
Minecraft 1.20.6

Reproduce steps:
Start the server
Type /ifp
See error

*Image is expired*

**Comment by heyxmirko** [comment]
The issue is fixed. Thanks for reporting!

**Comment by HaHaWTH** [comment]
> The issue is fixed. Thanks for reporting!

Nice work!
